### ISSUE TITLE
Single Demo Grasp test failure on master branch

### ISSUE THREAD

**Issue by stefaniapedrazzi** [opendr-eu/opendr#448]
It seems that there is a mismatch between the expected and used PIL version probably due to some updates in the dependencies.
Here is the error log:

======================================================================
ERROR: test_single_demo_grasp (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_single_demo_grasp
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/opendr/opendr/tests/sources/tools/control/single_demo_grasp/test_single_demo_grasp.py", line 20, in <module>
    from detectron2.modeling import build_model
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/modeling/__init__.py", line 20, in <module>
    from .meta_arch import (
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/modeling/meta_arch/__init__.py", line 6, in <module>
    from .panoptic_fpn import PanopticFPN
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/modeling/meta_arch/panoptic_fpn.py", line 14, in <module>
    from .rcnn import GeneralizedRCNN
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 9, in <module>
    from detectron2.data.detection_utils import convert_image_to_rgb
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/data/__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/data/transforms/__init__.py", line 4, in <module>
    from .transform import *
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/data/transforms/transform.py", line 36, in <module>
    class ExtentTransform(Transform):
  File "/home/runner/work/opendr/opendr/venv/lib/python3.8/site-packages/detectron2/data/transforms/transform.py", line 46, in ExtentTransform
    def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

**Comment by tsampazk** [comment]
This is now fixed by #454
