### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.msvccompiler'

### ISSUE THREAD

**Issue by tungngovn** [opendr-eu/opendr#515]
Hi.
Thanks for your great work. I got a problem during installing opendr-toolkit. Does anyone know how to fix it?

My system is Ubuntu 20.04.6 LTS
My command is: `pip install opendr-toolkit`
The error message:

```
Collecting av==8.0.3 (from opendr-toolkit-activity-recognition->opendr-toolkit)
  Using cached av-8.0.3.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tb9ljou9/av_52b676c3db1a427286d88630fc8b6890/setup.py", line 6, in <module>
          from distutils.msvccompiler import MSVCCompiler
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by passalis** [comment]
Thank you for your comments. We are investigating this issues. In the meanwhile, you can consider using docker images which shouldn't have been affected by this update.

**Comment by mulhamfetna** [comment]
This is a Python 3.12+ compatibility issue. The  module was deprecated in Python 3.10 and removed in Python 3.12.

The error occurs because the  package (PyAV) dependency uses  in its setup.py, which no longer exists in Python 3.12+.

**Workaround options:**

1. **Install  first** (which provides distutils compatibility):
   ```bash
   pip install --upgrade setuptools
   pip install av
   ```

2. **For a permanent fix**, the OpenDR maintainers could:
   - Pin  to version 12+ which migrated to setuptools
   - Or add  as a dependency in pyproject.toml

This is a known issue affecting many packages that depend on PyAV. The fix is straightforward but requires the maintainers to update dependency versions or add a setuptools requirement.

Would a PR updating the dependency constraints be welcome? I'd be happy to implement it.

**Comment by mulhamfetna** [comment]
Thank you for the approval and merge! The av>=12.0.0 update resolves the Python 3.12+ compatibility issue.
